import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

async function selectDate(page, date) {
  if (!await page.getByLabel('Fecha de consulta', { exact: true }).count()) await page.getByLabel('O elige tus fechas', { exact: true }).selectOption('day');
  await page.getByLabel('Fecha de consulta', { exact: true }).fill(date);
}

const sizes = [320, 390, 768, 1024, 1440];
for (const width of sizes) {
  test(`radioterapia: CRUD, día, horarios y tabla responsive a ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.goto('/');
    await page.getByLabel('Correo electrónico', { exact: true }).fill('admin@bitacoras.local');
    await page.getByLabel('Contraseña', { exact: true }).fill('Bitacoras2026!');
    await noOverflow();
    await page.getByRole('button', { name: 'Entrar al sistema' }).click();
    await expect(page.getByRole('heading', { name: 'Bitácora de radioterapia' })).toBeVisible();
    const patient = `Paciente de prueba María López Hernández ${width} ${Date.now()}`;
    await page.getByRole('button', { name: 'Registrar paciente', exact: true }).click();
    await page.getByLabel('Nombre del paciente *', { exact: true }).fill(patient);
    await page.getByLabel('RFC', { exact: true }).fill('lohm900101ab1');
    await expect(page.getByLabel('RFC', { exact: true })).toHaveValue('LOHM900101AB1');
    await page.getByLabel('Tipo de cirugía', { exact: true }).selectOption('Hospitalizado');
    await page.getByLabel('Día y fecha de atención *', { exact: true }).fill('2026-10-08');
    await page.getByLabel('Hora de llegada *', { exact: true }).fill('08:15');
    await page.getByLabel('Hora programada de tratamiento *', { exact: true }).fill('08:45');
    await expect(page.getByRole('dialog')).toContainText('jueves, 8 de octubre de 2026');
    await noOverflow();
    await page.getByRole('button', { name: 'Guardar registro', exact: true }).click();
    const record = page.getByRole('button', { name: patient, exact: true });
    await expect(record).toBeVisible();
    const row = page.locator('tbody tr').filter({ has: record });
    await expect(row).toContainText('jueves, 8 de octubre de 2026');
    await expect(row).toContainText('08:15');
    await expect(row).toContainText('08:45');
    await expect(row).toContainText('LOHM900101AB1');
    await expect(row).toContainText('Hospitalizado');
    const pivoted = width < 1440;
    await expect(row.locator('.tdBefore', { hasText: 'Paciente' })).toBeVisible({ visible: pivoted });
    expect(await row.evaluate(element => getComputedStyle(element).display)).toBe(pivoted ? 'grid' : 'table-row');
    await noOverflow();
    await page.screenshot({ path: `test-results/radioterapia-${width}.png`, fullPage: true });
    await page.getByRole('combobox', { name: 'Buscar pacientes' }).fill(patient);
    await expect(record).toBeVisible();
    await record.click();
    await expect(page.getByRole('dialog')).toContainText('08:45');
    await expect(page.getByRole('dialog')).toContainText('LOHM900101AB1');
    await expect(page.getByRole('dialog')).toContainText('Hospitalizado');
    await page.getByRole('button', { name: 'Editar registro', exact: true }).click();
    await expect(page.getByLabel('RFC', { exact: true })).toHaveValue('LOHM900101AB1');
    await expect(page.getByLabel('Tipo de cirugía', { exact: true })).toHaveValue('Hospitalizado');
    await page.getByLabel('RFC', { exact: true }).fill('LOHM900101AB2');
    await page.getByLabel('Tipo de cirugía', { exact: true }).selectOption('Ambulatorio');
    await page.getByLabel('Estado de atención *', { exact: true }).selectOption('Completada');
    await page.getByLabel('Hora programada de tratamiento *', { exact: true }).fill('09:00');
    await page.getByLabel('Observaciones', { exact: false }).fill('Registro ficticio para verificar el flujo.');
    await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('combobox', { name: 'Filtrar por estado' }).selectOption('Completada');
    await expect(record).toBeVisible();
    await expect(row).toContainText('Atendido');
    await expect(row).toContainText('LOHM900101AB2');
    await expect(row).toContainText('Ambulatorio');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Exportar CSV', exact: true }).click();
    const csv = await readFile(await (await downloadPromise).path(), 'utf8');
    expect(csv).toContain('"Día"');
    expect(csv).toContain('"RFC","Tipo de cirugía"');
    expect(csv).toContain(`"jueves","2026-10-08","${patient}","LOHM900101AB2","Ambulatorio","08:15","09:00","Atendido"`);
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Bitácora de radioterapia' })).toBeVisible();
    await page.getByLabel('O elige tus fechas').selectOption('day');
    await selectDate(page, '2026-10-08');
    await page.getByRole('combobox', { name: 'Buscar pacientes' }).fill(patient);
    await expect(record).toBeVisible();
    await expect(row).toContainText('09:00');
    await expect(row).toContainText('LOHM900101AB2');
    await expect(row).toContainText('Ambulatorio');
    await selectDate(page, '2026-10-09');
    await expect(record).toHaveCount(0);
    await selectDate(page, '2026-10-08');
    await expect(record).toBeVisible();
    await row.getByRole('button', { name: /^Eliminar RT-/ }).click();
    await page.getByRole('button', { name: 'Conservar registro' }).click();
    await expect(record).toBeVisible();
    await row.getByRole('button', { name: /^Eliminar RT-/ }).click();
    await page.getByRole('button', { name: 'Sí, eliminar', exact: true }).click();
    await expect(record).toHaveCount(0);
    await noOverflow();
    await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Iniciar sesión' })).toBeVisible();
    expect(errors).toEqual([]);
  });
}
