import { test, expect } from '@playwright/test';
import { chooseRowAction } from './helpers/row-actions.mjs';
import { readFile } from 'node:fs/promises';

async function selectDate(page, date) {
  const mobile = await page.evaluate(() => innerWidth < 640);
  if (mobile && !await page.locator('#custom-period-mobile').isVisible()) await page.getByRole('button', { name: 'Más filtros', exact: true }).click();
  const selector = page.locator(mobile ? '#custom-period-mobile' : '#custom-period');
  if (await selector.inputValue() !== 'day') await selector.selectOption('day');
  await page.locator(mobile ? '#consult-date-mobile' : '#consult-date').fill(date);
}

const sizes = [320, 390, 768, 1024, 1440];
for (const width of sizes) {
  test(`radioterapia: CRUD, día, horarios y tabla responsive a ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const noOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.goto('/');
    await page.getByLabel('Correo electrónico', { exact: true }).fill('admin@bitacoras.local');
    await page.getByLabel('Contraseña', { exact: true }).fill('Bitacoras2026!');
    await noOverflow();
    await page.getByRole('button', { name: 'Entrar al sistema' }).click();
    await expect(page.getByRole('heading', { name: 'Bitácora de radioterapia' })).toBeVisible();
    const patient = `Paciente de prueba María López Hernández ${width} ${Date.now()}`;
    await page.getByRole('button', { name: 'Registrar paciente', exact: true }).click();
    await page.getByLabel('Nombre del paciente *', { exact: true }).fill(patient);
    await page.getByLabel('RFC', { exact: true }).fill('lohm900101ab1');
    await expect(page.getByLabel('RFC', { exact: true })).toHaveValue('LOHM900101AB1');
    await page.getByLabel('Tipo de cirugía', { exact: true }).selectOption('Hospitalizado');
    const entitlement = page.getByRole('combobox', { name: 'Tipo de derechohabiencia', exact: true });
    await entitlement.click();
    await expect(page.getByRole('listbox', { name: 'Tipos de derechohabiencia' }).getByRole('option')).toHaveCount(24);
    await entitlement.fill('95');
    await expect(page.getByRole('option', { name: '95 IMSS BIENESTAR Hombre', exact: true })).toBeVisible();
    await entitlement.press('ArrowDown');
    await entitlement.press('Enter');
    await expect(entitlement).toHaveValue('95 · IMSS BIENESTAR Hombre');
    await page.getByLabel('Día y fecha de atención *', { exact: true }).fill('2026-10-08');
    await page.getByLabel('Hora programada de tratamiento *', { exact: true }).fill('08:45');
    await expect(page.getByRole('dialog')).toContainText('jueves, 8 de octubre de 2026');
    await noOverflow();
    await page.getByRole('button', { name: 'Guardar registro', exact: true }).click();
    const record = page.getByRole('button', { name: patient, exact: true });
    await expect(record).toBeVisible();
    const row = page.locator('tbody tr').filter({ has: record });
    const arrivalResponse = page.waitForResponse(response => response.url().includes('/arrival') && response.request().method() === 'POST');
    await chooseRowAction(page, row, 'Registrar llegada');
    const arrivalTime = (await (await arrivalResponse).json()).record.arrival_time;
    await expect(row).toContainText('Llegada registrada');
    await expect(row).toContainText('esperando');
    await row.getByRole('button', { name: /Avanzar estado a En tratamiento/ }).click();
    await expect(row).toContainText('En tratamiento');
    await record.click();
    await expect(page.getByRole('dialog')).toContainText('Inicio real del tratamiento');
    await expect(page.getByRole('dialog')).toContainText('Llegada registrada');
    await page.getByRole('button', { name: 'Cerrar', exact: true }).click();
    await expect(row).toContainText('jueves, 8 de octubre de 2026');
    await expect(row).toContainText('08:45');
    await expect(row).toContainText('LOHM900101AB1');
    await expect(row).toContainText('Hospitalizado');
    await expect(row).toContainText('95 · IMSS BIENESTAR Hombre');
    if (width < 640) await page.getByRole('button', { name: 'Más filtros', exact: true }).click();
    const pivoted = width < 1440;
    await expect(row.locator('.tdBefore', { hasText: 'Paciente' })).toBeVisible({ visible: pivoted });
    expect(await row.evaluate(element => getComputedStyle(element).display)).toBe(pivoted ? 'grid' : 'table-row');
    await noOverflow();
    await page.screenshot({ path: `test-results/radioterapia-${width}.png`, fullPage: true });
    await page.getByRole('combobox', { name: 'Buscar pacientes' }).fill(patient);
    await expect(record).toBeVisible();
    await record.click();
    await expect(page.getByRole('dialog')).toContainText('08:45');
    await expect(page.getByRole('dialog')).toContainText('LOHM900101AB1');
    await expect(page.getByRole('dialog')).toContainText('Hospitalizado');
    await expect(page.getByRole('dialog')).toContainText('95 · IMSS BIENESTAR Hombre');
    await page.getByRole('button', { name: 'Editar registro', exact: true }).click();
    await expect(page.getByLabel('RFC', { exact: true })).toHaveValue('LOHM900101AB1');
    await expect(page.getByLabel('Tipo de cirugía', { exact: true })).toHaveValue('Hospitalizado');
    await expect(entitlement).toHaveValue('95 · IMSS BIENESTAR Hombre');
    await entitlement.fill('inventado');
    await expect(page.getByRole('status').filter({ hasText: 'Sin coincidencias' })).toBeVisible();
    await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('button', { name: 'Limpiar tipo de derechohabiencia' }).click();
    await expect(entitlement).toHaveValue('');
    await entitlement.fill('conyuge');
    await expect(page.getByRole('listbox', { name: 'Tipos de derechohabiencia' }).getByRole('option')).toHaveCount(2);
    await entitlement.press('Escape');
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.getByRole('listbox', { name: 'Tipos de derechohabiencia' })).toHaveCount(0);
    await entitlement.click();
    await expect(page.getByRole('listbox', { name: 'Tipos de derechohabiencia' })).toBeVisible();
    await entitlement.fill('imss bienestar mujer');
    await page.getByRole('option', { name: '96 IMSS BIENESTAR Mujer', exact: true }).click();
    await expect(entitlement).toHaveValue('96 · IMSS BIENESTAR Mujer');
    await page.getByLabel('RFC', { exact: true }).fill('LOHM900101AB2');
    await page.getByLabel('Tipo de cirugía', { exact: true }).selectOption('Ambulatorio');
    await page.getByLabel('Estado de atención *', { exact: true }).selectOption('Completada');
    await page.getByLabel('Hora programada de tratamiento *', { exact: true }).fill('09:00');
    await page.getByLabel('Observaciones', { exact: false }).fill('Registro ficticio para verificar el flujo.');
    await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('combobox', { name: 'Filtrar por estado' }).selectOption('Completada');
    await expect(record).toBeVisible();
    await expect(row).toContainText('Atendido');
    await expect(row).toContainText('LOHM900101AB2');
    await expect(row).toContainText('Ambulatorio');
    await expect(row).toContainText('96 · IMSS BIENESTAR Mujer');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Exportar CSV', exact: true }).click();
    const csv = await readFile(await (await downloadPromise).path(), 'utf8');
    expect(csv).toContain('"Día"');
    expect(csv).toContain('"RFC","Tipo de cirugía"');
    expect(csv).toContain(`"jueves","2026-10-08","${patient}","LOHM900101AB2","Ambulatorio","96 · IMSS BIENESTAR Mujer","${arrivalTime}","09:00","Atendido"`);
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Bitácora de radioterapia' })).toBeVisible();
    if (width < 640) await page.getByRole('button', { name: 'Más filtros', exact: true }).click();
    await page.locator(width < 640 ? '#custom-period-mobile' : '#custom-period').selectOption('day');
    await selectDate(page, '2026-10-08');
    await page.getByRole('combobox', { name: 'Buscar pacientes' }).fill(patient);
    await expect(record).toBeVisible();
    await expect(row).toContainText('09:00');
    await expect(row).toContainText('LOHM900101AB2');
    await expect(row).toContainText('Ambulatorio');
    await expect(row).toContainText('96 · IMSS BIENESTAR Mujer');
    await selectDate(page, '2026-10-09');
    await expect(record).toHaveCount(0);
    await selectDate(page, '2026-10-08');
    await expect(record).toBeVisible();
    await chooseRowAction(page, row, 'Eliminar registro');
    await page.getByRole('button', { name: 'Conservar registro' }).click();
    await expect(record).toBeVisible();
    await chooseRowAction(page, row, 'Eliminar registro');
    await page.getByRole('button', { name: 'Sí, eliminar', exact: true }).click();
    await expect(record).toHaveCount(0);
    await noOverflow();
    await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Iniciar sesión' })).toBeVisible();
    expect(errors).toEqual([]);
  });
}
