import { entitlementLabel } from '../../shared/entitlement-types.mjs';
import { periodDescription, PERIODS } from './record-filters.mjs';

const escape = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
const statuses = { Pendiente: 'En espera', 'En proceso': 'En tratamiento', Completada: 'Atendido' };

export function reportHtml(records, { selection, query, status }) {
  const period = PERIODS.find(item => item.value === selection.period)?.label || (selection.period === 'day' ? 'Día específico' : 'Rango de fechas');
  const description = `${period}: ${periodDescription(selection)}${status ? ` · Estado: ${statuses[status]}` : ' · Todos los estados'}${query.trim() ? ` · Búsqueda: ${query.trim()}` : ''}`;
  const date = value => new Date(`${value}T12:00:00`).toLocaleDateString('es-MX', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' });
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Bitácora de radioterapia</title><style>
    *{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#35262b;margin:24px}h1{font-size:23px;color:#611232;margin:0 0 10px}p{font-size:12px;line-height:1.6}header{border-bottom:3px solid #9b2247;margin-bottom:20px;padding-bottom:12px}table{border-collapse:collapse;width:100%;font-size:10px;table-layout:fixed}th,td{border:1px solid #d9cdbb;text-align:left;padding:8px;vertical-align:top;overflow-wrap:anywhere}th{background:#f3ead3;color:#611232}td:last-child{white-space:pre-wrap}thead{display:table-header-group}tr{break-inside:avoid}footer{margin-top:16px;font-size:10px;color:#76646b}.toolbar{padding:16px;background:#faf5ea;border:1px solid #e8ddcc;border-radius:8px;margin-bottom:20px}button{background:#9b2247;color:white;border:0;border-radius:6px;padding:12px 18px;cursor:pointer}.table-wrap{overflow-x:auto}table{min-width:800px}@page{size:A4 landscape;margin:12mm}@media print{body{margin:0}.toolbar{display:none}.table-wrap{overflow:visible}table{min-width:0}th{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
    </style></head><body><div class="toolbar"><button id="print-report" type="button">Imprimir o guardar PDF</button><p>En el destino de impresión elige «Guardar como PDF» para descargar el reporte.</p></div><header><h1>Bitácora de radioterapia</h1><p>${escape(description)}</p><p><strong>${records.length} registros</strong> · Generado: ${escape(new Date().toLocaleString('es-MX'))}</p></header><main class="table-wrap"><table aria-label="Reporte de pacientes"><colgroup><col style="width:6%"><col style="width:10%"><col style="width:15%"><col style="width:10%"><col style="width:9%"><col style="width:12%"><col style="width:6%"><col style="width:8%"><col style="width:7%"><col style="width:17%"></colgroup><thead><tr>${['Folio', 'Día y fecha', 'Paciente', 'RFC', 'Tipo de cirugía', 'Tipo de derechohabiencia', 'Llegada', 'Tratamiento programado', 'Estado', 'Observaciones'].map(label => `<th>${escape(label)}</th>`).join('')}</tr></thead><tbody>${records.map(record => `<tr>${[`RT-${String(record.id).padStart(4, '0')}`, date(record.date), record.patient_name || 'Registro anterior sin paciente', record.rfc || 'Sin registrar', record.surgery_type || 'Sin registrar', entitlementLabel(record.entitlement_type), record.arrival_time || 'Sin registrar', record.treatment_time || 'Sin registrar', statuses[record.status] || record.status, record.observations || '—'].map(value => `<td>${escape(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></main><footer>Servicio de radioterapia · Todos los resultados de los filtros seleccionados.</footer></body></html>`;
}
